doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            place: App\Infrastructure\Persistence\Doctrine\Types\PlaceType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Infrastructure\Persistence\Doctrine:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mappings"
                prefix: 'App\Domain\Model'
                alias: App
            App\Infrastructure\Security:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Security/Mappings"
                prefix: 'App\Infrastructure\Security'
                alias: App
